name: Deploy Lambda to AWS

on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Go Lambda
      run: go build -o bin/main

    - name: Zip Lambda
      run: zip authorizer.zip bin

    - name: Upload Zip to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: g73-techchallenge-lambda-build
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        SOURCE_DIR: .
        DEST_DIR: /authorizer.zip