name: Deploy Lambda to AWS

on:
  push:
    tags:
    - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build Go Lambda
      run: go build -o bin/main

    - name: Zip Lambda
      uses: vimtor/action-zip@v1.2
      with:
        files: bin/
        dest: authorizer.zip

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Sync files to S3 bucket
      run: |
        aws s3 cp authorizer.zip s3://g73-techchallenge-lambda-build
        